### ISSUE TITLE
Timing types and `s` gate

### ISSUE THREAD

**Issue by zachschoenfeld33** [Qiskit/openqasm#112]
Timing units `dt, ns, µs, ms, s` are meant to be reserved types. However, the `pi/2` gate is typically denoted `s` (https://quantum-computing.ibm.com/docs/iqx/operations-glossary#s-gate). 

Perhaps the timing types should be capitalized or use `sec` to avoid this confusion?

**Comment by stevenheidel** [comment]
Does this lead to any ambiguities in the grammar? It means an awkward lexer token (seconds or s gate) but if the `s` for seconds only follows a number then there shouldn't be any confusion.

On a related note, I'd advocate for a `us` ascii synonym for `µs`.

**Comment by zachschoenfeld33** [comment]
It can be worked around in the grammar: https://github.com/Qiskit/openqasm/blob/a3132a4fd9a96383a94410449f9511235822b51a/source/grammar/qasm3.g4#L482, so I don't think there's any ambiguity. But it still could lead to confusing code.

I agree w/ us (that's what's in the antlr grammar PR currently)

**Comment by taalexander** [comment]
+1 for @stevenheidel proposal. The `s` gate is also not built-in and just part of the standard gate library which must be defined and included.

Please create a separate issue or PR to support both us and μs.
