### ISSUE TITLE
Ordering policy of evaluation in classical instructions

### ISSUE THREAD

**Issue by hhorii** [Qiskit/openqasm#113]
There is no description about evaluation order in classical instructions. I believe it is as most of programming languages (such as [python](https://www.informit.com/articles/article.aspx?p=459269&seqNum=11))

Parenthesized forms (with `(` and `)`) are necessary for users to control evaluation order.

If assignment is allowed in variable declaration (as shown in many examples), ordering of qubit specifications and variable specifications need to be defined. 

Example: ` int a = sub(a, b, c) q0, q1;`

If `sub` takes two qubits, `q0` and `q1` may be its arguments. However, `q1` can be recognized a declared variable as `int`.

I guess that qubit specifications should be weakest. A parenthesized form will be necessary if two qubit arguments are taken as ` int a = (sub(a, b, c) q0, q1);`.

**Comment by taalexander** [comment]
I agree a section on evaluation order is necessary. What you propose makes sense. We should follow the C evaluation order where it aligns.

**Comment by hhorii** [comment]
[The latest ANTLR file](https://github.com/Qiskit/openqasm/blob/a6ff5219ada57b3712917a82edd93e4c812c45cb/source/grammar/qasm3.g4) supports ordering of classical instructions.
