### ISSUE TITLE
Implicit size of types

### ISSUE THREAD

**Issue by zachschoenfeld33** [Qiskit/openqasm#114]
The specification states that there are no implicit sizes for OpenQASM types: https://qiskit.github.io/openqasm/language/types.html#integers.

However, in some of the examples, an implicit width is assumed: 
- https://github.com/Qiskit/openqasm/blob/master/examples/vqe.qasm#L77
- https://github.com/Qiskit/openqasm/blob/master/examples/scqec.qasm#L99
- https://github.com/Qiskit/openqasm/blob/master/examples/qec.qasm#L25

I think a default width would be nice, but either way the specification and examples should match.

**Comment by taalexander** [comment]
Please fix the implicit types in examples for now. We will consider a default at a later time.

**Comment by zachschoenfeld33** [comment]
I think we will almost certainly need some sort of default. Some examples have implicit casting. For instance, if you have
```const c = 5;
for i in [0:c-1] {...}
```
In this case, `i` is implicitly cast to an int type, rather than a `float[64]` (double floating pt used for `const`).

**Comment by zachschoenfeld33** [comment]
See https://github.com/Qiskit/openqasm/pull/119.
