### ISSUE TITLE
definition of ^ operator

### ISSUE THREAD

**Issue by hhorii** [Qiskit/openqasm#123]
A subsection [Classical bits and registers](https://qiskit.github.io/openqasm/language/classical.html#classical-bits-and-registers) describes as

> Classical registers and bits support bitwise operators and the corresponding assignment operators between registers of the same size: and `&`, or `|`, xor `^`.

and a subsection [Integers](https://qiskit.github.io/openqasm/language/classical.html#integers) describes as

> Integer types support addition `+`, subtraction `-`, multiplication `*`, and integer division `/`; the corresponding assignments `+=`, `-=`, `*=`, and `/=`; as well as increment `++` and decrement `--`.

In a surface code in [examples](https://github.com/Qiskit/openqasm/blob/master/examples/scqec.qasm), `^` is used as "power" operation for integers, I guess.

```
const d = 3;         // code distance
const m = 10;        // number of syndrome measurement cycles
const shots = 1000;  // number of samples
const n = d^2;       // number of code qubits
```

If operator is like Python, `^` is XOR and `**` is POWER.

**Comment by zachschoenfeld33** [comment]
I think `**` should be power to allow for the XOR `^`.

**Comment by ajavadia** [comment]
I agree let's use ** for power.

**Comment by zachschoenfeld33** [comment]
@hhorii would you be able to update the examples and document to reflect this? We will also want to update the ANTLR grammar
