### ISSUE TITLE
cast from uint to bool

### ISSUE THREAD

**Issue by hhorii** [Qiskit/openqasm#125]
I think cast operation from `uint` to `bool` is not clearly defined in the specification. I'm not sure following two cast operations in [adder.qasm](https://github.com/Qiskit/openqasm/blob/master/examples/adder.qasm#L32-L33) are valid or not:

```
uint[4] a_in = 1;  // a = 0001
uint[4] b_in = 15; // b = 1111
...
  if(bool(ain[i])) x a[i];
  if(bool(bin[i])) x b[i]; 
```
(BTW, variable names (`ain` and `bin` should be `a_in` and `b_in`).)

I guess that they are
```
  if((bit[4](a_in))[i]) x a[i];
  if((bit[4](b_in))[i]) x b[i];
```

or does `uint[4] a_in` allow bit access with `a_in[i]` (as `creg`)?

**Comment by taalexander** [comment]
Its unclear to me if we support bit, level access to all types. This may be difficult to implement, and casting may be more straightforward. Thoughts @blakejohnson?
