### ISSUE TITLE
Looping Constructs

### ISSUE THREAD

**Issue by zachschoenfeld33** [Qiskit/openqasm#128]
There appears to be an inconsistency between the Python loop style (no parentheses) and the Java/C loop Style (with parenthesis).

For `if/while`, OpenQasm has:
`if (bool) { body }` and `while (bool) { body }`, but `for condition { body }`.

We should have consistency. Given the Python-like constructs already in the language (specifically the membership test `a in b`), I would advocate for removing the parentheses (or letting them be optional at least).

**Comment by levbishop** [comment]
Agree they should be consistent. I don't have a strong opinion on with/without parens but I lean slightly towards requiring them.

**Comment by zachschoenfeld33** [comment]
I also don't have a strong opinion. I would be fine adding everywhere. It does made the code clearer. Does anyone else have strong opinions before I open a PR updating this?

**Comment by stevenheidel** [comment]
I would also lean towards requiring them

**Comment by zachschoenfeld33** [comment]
Closing this for now. We can update later if the need arises.
