### ISSUE TITLE
Feedback on spec

### ISSUE THREAD

**Issue by Travis-S-IBM** [Qiskit/openqasm#129]
In reading through the specification today, some items stood out as benefiting from clarification or editing. Sharing here.

## [Types and Casting](https://qiskit.github.io/openqasm/language/types.html)

* The text implicitly introduces the idea of "program qubits" via juxtaposition with "physical qubits". Presumably this distinction is conceptually important for the grammar and specification. To that end, I'd suggest a paragraph on program qubits, their properties, and any available information on mapping from program to physical qubits.

Separately, is the intention of this specification to introduce "program qubits" as a standard terminology into the circuit compilation lexicon? If so, then it's all the more important to call it out explicitly.

* There's no example on this page of how to use the `stretch` type. While there are some examples in the [Circuit timing page](https://qiskit.github.io/openqasm/language/delays.html), there should be an example here.

## [Gates](https://qiskit.github.io/openqasm/language/gates.html)

* The page introduces the idea of "quantum instruction" without definition. The [Built in quantum instructions page](https://qiskit.github.io/openqasm/language/insts.html) also doesn't really define them. Would there be a straightforward explanation that could be added?

* The example for a CX gate uses \oplus, not \otimes. Is that intentional? Separately, this example also introduces a different bit ordering than is commonly used; it should be called out more clearly.

* It's unclear to me why the example below (taken from the page) is the case. In particular, it seems `qr0` is a 1-qubit register, while `qr2` and `qr3` are 2-qubit, and `qr2` is 3-qubit. So wouldn't both applications of g be incorrect?
```
gate g qb0, qb1, qb2, qb3
{
  // body
}
qubit qr0[1];
qubit qr1[2];
qubit qr2[3];
qubit qr3[2];
g qr0[0], qr1, qr2[0], qr3; // ok
g qr0[0], qr2, qr1[0], qr3; // error!
```

## [Built-in quantum instructions](https://qiskit.github.io/openqasm/language/insts.html)

* The declaration of the classical bits in the example below is incorrect, no? Shouldn't it be `bits bit[10]`?
```
// Initialize, flip and measure an array of 10 qubits
qubit qubits[10];
bit[10] bits;
x qubits;
bits = measure qubits
```

## [Classical instructions](https://qiskit.github.io/openqasm/language/classical.html)

* In the example below, the loop goes over every _even_ integer, no?
```
// loop over every positive number from 0 to 20 using an indexset
for i in [0:2:20] {
   // do something
}
```

## [Subroutines](https://qiskit.github.io/openqasm/language/subroutines.html)

* A couple of times on this page, constants are defined without assigning them values. Is that permissible?
```
const n = /* some size, known at compile time */;
```
and
```
const n = /* size of c + size of c2 */;
```

## [Pulse-level descriptions of gates and measurement](https://qiskit.github.io/openqasm/language/pulses.html)

* This page doesn't make clear whether a `defcal` of a given gate can itself be parameterized. I should think this would be a common use case (for example, tuning up gates). Is that use case covered by the specification? If so, an example would bbe nice.

-----------------

Finally, there isn't a page talking about the compilation of OpenQASM 3.0 programs. Given the fact the specification calls out program vs. physical qubits, having some kind of documentation explaining how the compilation happens would be helpful.

**Comment by taalexander** [comment]
Thank you for your feedback @Travis-S-IBM. I agree with much of the clarity highlights, would it be to much to ask you to clone and fix these to be more clear? We accept all contributions 😄 . Below I've included some more specific responses.

> The example for a CX gate uses \oplus, not \otimes. Is that intentional? Separately, this example also introduces a different bit ordering than is commonly used; it should be called out more clearly.

This is an error.

> The declaration of the classical bits in the example below is incorrect, no? Shouldn't it be bits bit[10]?

No, this is currently c-style syntax for declaration. However, there is inconsistent usage of this, see #117.

> In the example below, the loop goes over every even integer, no?

No, it goes in intervals of 2.

> A couple of times on this page, constants are defined without assigning them values. Is that permissible?

This for example only. It is not executable. If you have ideas how to rewrite these to be valid we would appreciate updates.

> This page doesn't make clear whether a defcal of a given gate can itself be parameterized. I should think this would be a common use case (for example, tuning up gates). Is that use case covered by the specification? If so, an example would bbe nice.

The defcal receives the same parameters of the gate and is free to use them to tune up the gate, eg., by defining a `gate rabi(amp)`. Otherwise, such parameters should be in an outerloop of OpenQasm executions.

**Comment by Travis-S-IBM** [comment]
@taalexander Ok. Will do.

One small point: this index set ([0:2:20]) should output 0, 2, 4, 6, ..., 18 -- correct? If so, then that is every even number from 2 to 18, plus 0.

**Comment by taalexander** [comment]
Thank you 😊.

> One small point: this index set ([0:2:20]) should output 0, 2, 4, 6, ..., 18 -- correct? If so, then that is every even number from 2 to 18, plus 0.

Yes, it is zero inclusive. My apologies, in your initial comment my eyes missed the word "even".

**Comment by zachschoenfeld33** [comment]
@Travis-S this issue appears to be stale--can we close it and then open specific issues if any particular concerns need to be addressed?

**Comment by Travis-S-IBM** [comment]
Yes
