### ISSUE TITLE
OpenQASM Paramaterized Circuits may require a macro preprocessor

### ISSUE THREAD

**Issue by jwoehr** [Qiskit/openqasm#138]
As [Felix Truger](https://github.com/it14078) ( qiskit slack `@felix truger` ) has pointed out elsewhere, the notion of a Parameterized QuantumCircuit is absent from OpenQASM. In a classic assembler, this would be the role of a macro preprocessor. Such a preprocessor is trivial to implement, for instance in [m4](https://www.gnu.org/software/m4/).

**Comment by hhorii** [comment]
This is just a comment.

In [examples/vqe.qasm](https://github.com/Qiskit/openqasm/blob/e921247530923467a8dc59baf512e508284608fc/examples/vqe.qasm), a kernel function `get_parameter` handles parameters.

```
// Parameters could be written to local variables for this
// iteration, but we will request them using kernel functions
kernel get_parameter(uint[prec], uint[prec]) -> angle[prec];
```

**Comment by taalexander** [comment]
Please see #127, parameterization will be handled as an entry point to the QASM program. The caller will be able to reuse a compiled program with new inputs. This is a more powerful form of parameterization as it allows compiled code reuse in the hardware with variable inputs. This will lead to significant performance enhancements.

It would certainly be possible to support further macro preprocessing on top of OpenQASM3 but this is currently out of scope.

**Comment by jwoehr** [comment]
@hhorii @taalexander thank you for your replies. It certainly sounds like parameterization of entire QASM programs is well covered in the OpenQASM 3 approach. When a reference implementation is available, we'll give it a test drive.

**Comment by taalexander** [comment]
Glad to hear it, we're hard at work exposing the implementation. Closing this issue.
