### ISSUE TITLE
[ANTLR] intermediate return statement

### ISSUE THREAD

**Issue by hhorii** [Qiskit/openqasm#139]
[Subroutine](https://qiskit.github.io/openqasm/language/subroutines.html) can return value and return statements must be at the end of subroutine in [the current grammar](https://github.com/Qiskit/openqasm/blob/0950d4ca070ffc6d99cee289eaa540b8eab6f14e/source/grammar/qasm3.g4#L385-L387).
```
subroutineBlock
    : LBRACE statement* returnStatement? RBRACE
    ;
```

This means that a return statement can not be in branch bodies.

**Comment by zachschoenfeld33** [comment]
This is a fair point--will add a PR to update this.

**Comment by zachschoenfeld33** [comment]
@hhorii pls see https://github.com/Qiskit/openqasm/pull/140.

**Comment by hhorii** [comment]
I confirmed that #140 supports intermediate return. Once it is merged, this issue can be closed.

**Comment by zachschoenfeld33** [comment]
Closing as #140 is merged
