### ISSUE TITLE
[ANTLR] flexible variable initialization

### ISSUE THREAD

**Issue by hhorii** [Qiskit/openqasm#141]
Currently, `classicalDeclaration` allows variable initialization only for "all" variables in a statement. Therefore, `int[32] i = 10, j;` is not accepted though C accepts it.

```
classicalDeclaration
    : singleDesignatorDeclaration
    | doubleDesignatorDeclaration
    | noDesignatorDeclaration
    | bitDeclaration
    ;

singleDesignatorDeclaration
    : singleDesignatorType designator ( identifierList | equalsAssignmentList )
    ;

identifierList
    : ( Identifier COMMA )* Identifier
    ;

equalsAssignmentList
    : ( Identifier equalsExpression COMMA)* Identifier equalsExpression
    ;

equalsExpression
    : EQUALS expression
    ;
```

**Comment by zachschoenfeld33** [comment]
Have you tested this? The `( identifierList | equalsAssignmentList )` is meant to serve this purpose.

**Comment by hhorii** [comment]
@zachschoenfeld33 I tested it with the following QASM and encountered an error with a message `line 4:17 no viable alternative at input 'j;'`.
```
OPENQASM 3;
include "stdgates.inc";

int[32] i = 10, j;
```

Following `singleDesignatorDeclaration` can parse this QASM.
```
singleDesignatorDeclaration
    : singleDesignatorType designator ( Identifier equalsExpression? COMMA )* Identifier equalsExpression?
    ;
```

**Comment by zachschoenfeld33** [comment]
Yes you are right. That is the solution. Might be good to define a new list with that rule you list above.

**Comment by zachschoenfeld33** [comment]
My bad. Apparently this is not meant to be valid in the language. We only allow no initialization or all variables initialized, so
```
int[32] i, j;
int[32] i=3,j=4;
```
I believe we should close the issue. If you feel adamantly, we should open up the discussion to others.
