### ISSUE TITLE
[ANTLR] gphase needs to take expression

### ISSUE THREAD

**Issue by hhorii** [Qiskit/openqasm#142]
Example of `gphase` [in the spec](https://qiskit.github.io/openqasm/language/gates.html?highlight=gphase
)  is `gphase(-tau/2);` and this `-tau/2` looks `expression` in the grammar. However, [current grammar](https://github.com/Qiskit/openqasm/blob/0b3fe89214dedd6831926ee56ca5cbf599f423f5/source/grammar/qasm3.g4#L233-L235
) takes `Identifier`.

```
quantumPhase
    : 'gphase' LPAREN Identifier RPAREN
    ;
```

**Comment by zachschoenfeld33** [comment]
fixed in https://github.com/Qiskit/openqasm/pull/195.
