### ISSUE TITLE
[ANTLR] Duplication of return types in kernel declaration 

### ISSUE THREAD

**Issue by hhorii** [Qiskit/openqasm#143]
Currently, `kernelDeclaration` is defined as follows [in the grammar](https://github.com/Qiskit/openqasm/blob/0b3fe89214dedd6831926ee56ca5cbf599f423f5/source/grammar/qasm3.g4#L233-L235).

```
kernelDeclaration
    : 'kernel' Identifier ( LPAREN classicalTypeList? RPAREN )? returnSignature?
    classicalType? SEMICOLON
```

This `returnSignature` is defined as follows, while including `classicalType`.

```
returnSignature
    : ARROW classicalType
    ;
```

On the other hand, `classicalType` is defined in `kernelDeclaration` after this `returnSignature`. Therefore, from the grammar, two `classicalType` can be listed in a kernel declaration after argument specification.

If both of `ARROW classicalType` and `classicalType` are allowed to specify a return type, the current grammar may be reasonable (though `(returnSignature? | classicalType?)` is better). If not, `classicalType?` is not necessary in `kernelDeclaration`.

Currently, this qasm can be parsed.
```
OPENQASM 3;
kernel test_kernel (int[64], int[64], int[64]) -> int[64] int[64];
```

**Comment by zachschoenfeld33** [comment]
Good catch. Should only be a single return type. You can remove the additional `classicalType?` following `returnSignature?`. It should be done how subroutines do it, which are valid.

**Comment by zachschoenfeld33** [comment]
Fixed in https://github.com/Qiskit/openqasm/pull/195
