### ISSUE TITLE
Lexes without semantics should be optional

### ISSUE THREAD

**Issue by jwoehr** [Qiskit/openqasm#166]
Lexes like

- `@` in Quantum Gate Modifiers (language/gates.html#quantum-gate-modifiers)
- `,` separating qreg/qubit arguments to gate directives

that possess no semantics and merely serve as road braille for the user should be admissible but optional.

E.g., taking an example from Quantum Gate Modifiers:

```
// Define a controlled Rz operation using the ctrl gate modifier.
gate crz(θ) q1, q2 {
    ctrl @ U(θ, 0, 0) q1, q2;
}
```
could just as easily be written
```
// Define a controlled Rz operation using the ctrl gate modifier.
gate crz(θ) q1 q2 {
    ctrl U(θ, 0, 0) q1 q2;
}
```
This observation does not apply to commas (`,`) used to separate gate parameter arguments which do possess semantics where expressions can appear.

**Comment by steleman** [comment]
> Lexes like
> 
>     * `@` in Quantum Gate Modifiers (language/gates.html#quantum-gate-modifiers)
> 
>     * `,` separating qreg/qubit arguments to gate directives
> 
> 
> that possess no semantics and merely serve as road braille for the user should be admissible but optional.
> 
> E.g., taking an example from Quantum Gate Modifiers:
> 
> ```
> // Define a controlled Rz operation using the ctrl gate modifier.
> gate crz(θ) q1, q2 {
>     ctrl @ U(θ, 0, 0) q1, q2;
> }
> ```
> 
> could just as easily be written
> 
> ```
> // Define a controlled Rz operation using the ctrl gate modifier.
> gate crz(θ) q1 q2 {
>     ctrl U(θ, 0, 0) q1 q2;
> }
> ```
> 
> This observation does not apply to commas (`,`) used to separate gate parameter arguments which do possess semantics where expressions can appear.

The comma operator has semantics.

**Comment by jwoehr** [comment]
What's the semantics of the comma? I may be wrong, but I'm having trouble imagining an example where a gate invocation would become ambiguous without the commas.

**Comment by steleman** [comment]
> What's the semantics of the comma? I may be wrong, but I'm having trouble imagining an example where a gate invocation would become ambiguous without the commas.

The comma operator creates lists and/or enumerations. That's the semantics.

Arguments and/or parameters passed to functions, gates, kernels, etc. are lists.

**Comment by jwoehr** [comment]
My position is such commas should be "permitted but not required".

There is no parsing ambiguity omitting the commas (it seems to me).

The LALR syntactic _list_-iness of the qubit/qreg targets of a gate operation is not a concern for the user.

They are a list with or without the commas.

`inv mygate(`_some_`,` _params_`,` _possibly_`,` _expressions_`) qx qy;`

Again, I refrain from applying my plumb line to the commas separating parenthesized gate parameters because expressions might appear there.

**Comment by steleman** [comment]
> My position is such commas should be "permitted but not required".

Noted.

> The LALR syntactic _list_-iness of the qubit/qreg targets of a gate operation is not a concern for the user.

It is a concern to the compiler writer, and I am speaking as such.

**Comment by jwoehr** [comment]
Ha, @steleman ! As @taalexander has already found out, I have been lying in wait for someone to offer that justification!

In response, I quote to you from **IBM's premier language designer of the 20th century**:

_The general principle is that very few people have to implement interpreters or compilers for a language, whereas millions of people have to use and live with the language. One should therefore optimize for the millions, rather than the few. Compiler writers didn't love me for that, because Rexx got to be a hard language to interpret or compile, but I think it has paid off for people in general, certainly programmers in general._

IBM Fellow Emeritus Michael Cowlishaw, [A Conversation with Michael Cowlishaw](https://www.drdobbs.com/a-conversation-with-michael-cowlishaw/184409842) by Jack Woehr,  Dr. Dobb's Journal, March 01, 1996

**Comment by jwoehr** [comment]
Hmm I tried this and the whole test suite passed.
The problem of permit-but-not-require commas in index identifiers is probably more complex than this but it doesn't look intractable.

```
$ git diff
diff --git a/source/grammar/qasm3.g4 b/source/grammar/qasm3.g4
index c789c09..f381e13 100644
--- a/source/grammar/qasm3.g4
+++ b/source/grammar/qasm3.g4
@@ -177,6 +177,7 @@ indexIdentifier
 
 indexIdentifierList
     : ( indexIdentifier COMMA )* indexIdentifier
+    | ( indexIdentifier )* indexIdentifier
     ;
 
 indexEqualsAssignmentList
diff --git a/source/grammar/tests/outputs/declaration.yaml b/source/grammar/tests/outputs/declaration.yaml
index 08c27e8..dc2345b 100644
--- a/source/grammar/tests/outputs/declaration.yaml
+++ b/source/grammar/tests/outputs/declaration.yaml
@@ -1,7 +1,7 @@
 # indent w/ 2 spaces
 source: |
   int[10] x, y;
-  qubit q1[6], q2;
+  qubit q1[6] q2;
   bit b1[4]="0100", b2 = "1";
   bool m=True, n=bool(b2);
   const c = 5.5e3, d=5;
@@ -39,7 +39,6 @@ reference: |
                   expressionTerminator
                     6
               ]
-            ,
             indexIdentifier
               q2
         ;
```

**Comment by jwoehr** [comment]
Anyway, I went further with this, but there is no point in proceeding if it's not of interest to the team. Commas, at-signs, (`@`), if the team wants them in the language, that's the way it's going to be.
