### ISSUE TITLE
Typo in rotation operator definition

### ISSUE THREAD

**Issue by ku-antum** [QISKit/openqasm#17]
In line 130 of spec/qasm2.tex there should be a `\phi` instead of `\theta`, i.e.`$R_z(\phi)=\mathrm{exp}(-i\phi Z/2)$` instead of `$R_z(\phi)=\mathrm{exp}(-i\theta Z/2)$`.

**Comment by jaygambetta** [comment]
This is correct. We are current moving it from latex to Markdown so that it is simple for people to edit and fix. We will make this correction after we make this conversion.
