### ISSUE TITLE
Will the "_" in the gate name be deprecated?

### ISSUE THREAD

**Issue by DevelopDaily** [Qiskit/openqasm#170]
The _IBM Quantum Composer_ does not allow `_` in the gate name. For example,

```
gate abc1 q // Good
{
}

gate abc_1 q // Bad
{
}
```

The OpenQASM 2.0 clearly specifies the validity of the `_` in the gate name. Have you asked the _IBM Quantum Composer_ people to stop using `_`? Or, is that just an outright bug in their parser? 

The `_` is so useful. I cannot imagine any reason to deprecate it.

**Comment by taalexander** [comment]
This seems like a bug in the IBM Q Composer specifically. I will raise internally with this team.

**Comment by taalexander** [comment]
This is confirmed a bug and an internal ticket has been opened to fix.

**Comment by zachschoenfeld33** [comment]
@taalexander can you link that issue for the IBM Quantum Composer and close this issue (as it is not a bug within the OpenQASM3 specification)?

**Comment by stevenheidel** [comment]
+1 to closing this since it's not an OpenQASM issue

**Comment by zachschoenfeld33** [comment]
Agreed.
