### ISSUE TITLE
msd.qasm uses undefined variables: scratch_0 and scratch_1

### ISSUE THREAD

**Issue by hhorii** [Qiskit/openqasm#173]
Two variables `scratch_0` and `scratch_1` are used though they are not defined in examples/msd.qasm:
https://github.com/Qiskit/openqasm/blob/a20a746e789a18e0f677f8be4faea847bbe9bcae/examples/msd.qasm#L121-L122

Because  `distill` resets all of 2nd qubits, they may be replaced with `scratch`.

**Comment by zachschoenfeld33** [comment]
Good point. Probably should be indexed, aka `scratch[0]` and `scratch[1]`.

**Comment by zachschoenfeld33** [comment]
Closed via https://github.com/Qiskit/openqasm/pull/194.
