### ISSUE TITLE
varteleport.qasm attemps to cast from qubit to bit implicitly

### ISSUE THREAD

**Issue by hhorii** [Qiskit/openqasm#174]
A qubit `bp[0]` is assigned to a classical variable `pf[1]`.
https://github.com/Qiskit/openqasm/blob/a20a746e789a18e0f677f8be4faea847bbe9bcae/examples/varteleport.qasm#L36

I guess that `measure` is necessary before `bp[0]`.

**Comment by zachschoenfeld33** [comment]
This looks like a bug--needs a `measure` as you say.
