### ISSUE TITLE
[ANTLR] branchingStatement should take expression

### ISSUE THREAD

**Issue by hhorii** [Qiskit/openqasm#176]
`branchingStatement`  takes `booleanExpression` for its test.

```
branchingStatement
    : 'if' LPAREN booleanExpression RPAREN programBlock ( 'else' programBlock )?
    ;
```

However, this test can be `bool` type variable or subroutine/kernel calls that return `bool `. I believe that we should use `expression` instead of booleanExpression after integrating `booleanExpression` into the expression hierarchy.

**Comment by zachschoenfeld33** [comment]
This is already fixed. See https://github.com/Qiskit/openqasm/blob/master/source/grammar/qasm3.g4#L370.
