### ISSUE TITLE
[ANTLR] 'true' and 'false' are expressionTerminator

### ISSUE THREAD

**Issue by hhorii** [Qiskit/openqasm#179]
The spec defines `true` and `false` .

> There is a Boolean type bool name; that takes values `true` or `false`.
https://qiskit.github.io/openqasm/language/types.html#boolean-types

Currently, `true` and `false` are pased as `Identity`.

**Comment by zachschoenfeld33** [comment]
@hhorii would you mind adding a PR fixing this when you can?
