### ISSUE TITLE
[ANTLR] delay instruction will be parsed to expressionStatement

### ISSUE THREAD

**Issue by godott** [Qiskit/openqasm#185]
1. Current parsing rule for `expressionStatement` is too general. Timing statement (which is also quantumStatement) like `delay[lengthof(a)] q[2], q[3];` is parsed as `expressionStatement`. `expressionStatement` has to be more specifically defined. 

2. At the same time, it means `delay[lengthof(a)]` is parsed as `indexIdentifier` as opposed to `TimingInstruction`. The solution can be defining `DELAY: 'delay'` so it will overwrite `identifier`.

**Comment by godott** [comment]
From my observasion, the only expressionStatement is incrementors like `i++`.

**Comment by hhorii** [comment]
I parsed `delay[lengthof(a)] q[2], q[3];` with the master 89e93e7, and then got following tree:
```
program
  header
  statement
    quantumStatement
      timingStatement
        timingInstruction
          timingInstructionName
            delay
          designator
            [
            expression
              expressionTerminator
                builtInCall
                  builtInMath
                    lengthof
                  (
                  expressionList
                    expression
                      expressionTerminator
                        a
                  )
            ]
          indexIdentifierList
            indexIdentifier
              q
              [
              expressionList
                expression
                  expressionTerminator
                    2
              ]
            ,
            indexIdentifier
              q
              [
              expressionList
                expression
                  expressionTerminator
                    3
              ]
        ;
```

is this issue resolved in your environment? > @godott
