### ISSUE TITLE
declaring physical-qubits

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/openqasm#198]
In section [Types and Casting -> Physical Qubits](https://qiskit.github.io/openqasm/language/types.html?highlight=angle#physical-qubits), the specification refers to the possibility of referring to  *Physical Qubits*. However, the specification is not explicit about declaring physical qubits or if they *just exists*. A clarification would be great.

**Comment by zachschoenfeld33** [comment]
@1ucian0 can you add a PR clarifying the language? A general qubit can be declared via an identifier. If we decide we want to reference a particular qubit in the hardware, we use a physical qubit reference. Physical qubits must be declared before use, which is done w/ the `qubit $N` syntax.

**Comment by blakejohnson** [comment]
I think the notion is that they __just exist__. So, no need to declare them.

**Comment by taalexander** [comment]
I prefer taking the approach where we declare them in some standardized header that may be included. This seems more consistent for the language, and we do not have to worry about components popping into existence.

Eg.,
```qasm
// backend.qasm

qubit $0;
qubit $1;
```

```qasm
// user_program.qasm

OPENQASM 3.0;

include "backend.qasm";
...
defcal cx $0, $1 {
   ....
}
```

**Comment by jwoehr** [comment]
I wrote earlier against the '$' syntax, but if the '$' syntax prevails, then they probably don't require declaration, as the syntax is apparently unambiguous and easy to parse.

**Comment by blakejohnson** [comment]
@taalexander to me, physical qubits are akin to registers in a traditional CPU which are not declared --- they _just exist_. Maybe it would be helpful to tell your compiler what physical qubits exist for a particular backend, but that seems like something outside the language itself.
