### ISSUE TITLE
Paper: Add `input/output` types for parametric programs

### ISSUE THREAD

**Issue by zachschoenfeld33** [Qiskit/openqasm#205]
Need to add `input/output` types for OpenQASM programs into the spec. See pp. 22, 23, 24 of https://arxiv.org/pdf/2104.14722.pdf. VQE example should be updated (or a new one added to compare).

**Comment by stevenheidel** [comment]
@karalekas volunteered to write this into the spec.

There's also an issue to resolve in the examples which sometimes use 'input' and 'output' as variable names.

**Comment by zachschoenfeld33** [comment]
Closing via #225.
