### ISSUE TITLE
extend the grammar with negctrl gate modifier

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/openqasm#219]
The paper https://arxiv.org/abs/2104.14722 introduces `negctrl` for open controlled gates that the grammar currently does not support. The OpenQASM3 grammar needs to be extended with `negctrl`.

**Comment by zachschoenfeld33** [comment]
See https://github.com/Qiskit/openqasm/pull/203.

**Comment by 1ucian0** [comment]
closing as duplicated with #203
