### ISSUE TITLE
AST from ANTLR4 grammar

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/openqasm#220]
Many applications can make a good use of an AST visitor. In my case, for "unparsing". There were many attempts to create ASTs, but they fall behind quickly, as the grammar is a moving target.

If I understand correctly the ANTLR documentation, it is possible to annotate the grammar with semantic actions. This would allow to keep the AST generation in sync with the grammar.

**Comment by taalexander** [comment]
I believe this may be within the scope of the working group proposed here - https://github.com/Qiskit/openqasm/pull/221#issuecomment-862545336.

**Comment by jwoehr** [comment]
For reference see [New OpenQASM2 translator based on ANTLR4 grammar](https://github.com/Qiskit/qiskit-terra/pull/6657)

**Comment by jakelishman** [comment]
Closing this as fixed with the merge of #269.
