### ISSUE TITLE
[Draft] verbatim modifier for box

### ISSUE THREAD

**Issue by shiyunon** [Qiskit/openqasm#224]
# `verbatim` modifier for `box`

In this draft, we propose the introduction of the `verbatim` modifier for `box`. `verbatim` is a compiler flag to notify the compiler to not touch the decorated `box`. The purpose is to give users precise control of the boxed operations without them being transformed, optimized or re-synthesized by the compiler. 

An example is as follows:

```
// verbatim box demo
OPENQASM 3;
include "stdgates.inc";

z $0;

verbatim box {
     delay[20ns] $1;
     cx $0, $1;
     x $1;
     x $1;
}

z $0;
```

In the above example, the two `x`  gates in the `verbatim box` will not be merged (cancelled) by a compiler. However, just same as `box` without the modifier, gates around the verbatim box can commute through the box and cancel each other. Thus, the above two `Z` gates are allowed to be moved over the box and cancelled by the compiler.

## What is preserved by the `verbatim` modifier

The following are preserved:

* The order and length of the gate sequences (so no gates are moved or cancelled, no gate insertion as well).
* Linking of native gates to calibration definitions. Native gates will be directly linked to their `defcal` and will not be replaced with any other (potentially more optimized) pulse calibrations by any compiler passes .
* Timing and duration. No compiler optimization passes can alter the timing operations specified in the box, even if the new scheduling is functionally equivalent to the original and more optimized. But the compiler is allowed to resolve undetermined timing/duration of gates.
* Qubit mapping. No temporary physical qubit re-mapping, ancilla qubit or SWAP gate insertion is allowed. If the circuit is not mapped at the end of the compilation, the compiler will throw an error.

In other words, any compiler passes other than  (1)  timing/duration resolution and (2) calibration linking should not be modifying the code in a `verbatim box`.

## What is disallowed in a `verbatim` box

As mentioned above, the only two compiler passes that look inside a verbatim box are (1)  timing/duration resolution and (2) calibration linking. As a result, having any of the following high-level constructs in a verbatim box will result in a runtime error since related compiler passes will not be able to look inside to properly compile these:

* Virtual qubits

* Composite gates without a defcal

* Subroutine/kernel calls

* Any other language constructs cannot be compiled down to determined pulse schedules by the timing/duration resolution compiler pass and the calibration linking pass.

## What is allowed in a `verbatim` box

* `barrier`  is allowed but will raise a compiler warning since it takes no effects.

* Language constructs that can be compiled down to determined pulse schedules by the timing/duration resolution compiler pass and the calibration linking pass.

* Assigning a duration to a `verbatim` box is allowed:

```
verbatim box [1ms] {
    stretch a;

    delay[a] $0;
    cx $0, $1;
    cx $0, $1;
    delay[a] $0;
}
```

The above codes would be useful for centering the two cx gates. 

## `verbatim` levels

As shown in some of the use cases below (e.g. the flag qubit scheme), it’s inconvenient to only allow gates with `defcal` to be inside a `verbatim` box.  We introduce level 1 `verbatim` box to give users more granular control of a `verbatim` box. We propose:

* the default verbatim box to be level 0. In the default verbatim box, no composite gates are allowed.
* level 1 be denoted as `verbatim(1) box {...}`. We allow virtual qubits inside a level 1 box. 
* We allow virtual qubits and composite  inside a level 2 box. 

```
gate cz a, b{ // assume cx, hadamard has a defcal, but not cz.
    h a;
    cx a, b;
    h a;
}

verbatim(2) box {
     cz q[0], q[1]; // level 2 box accept and decompose it.

```

## `inline` modifier

As an alternative to level 2 verbatim box, we can also provide an `inline` modifier to allow composite gates. This `inline` approach will improve the readability of the program and is closely aligned to the C language. An example is as follows:

```
gate cz a, b{ // assume cx, hadamard has a defcal
    h a;
    cx a, b;
    h a;
}

verbatim(1) inline box {
    cz q[0], q[1]; // with inline modifier, this piece of code will not raise an error.
}
```

# Use cases

## **Digital zero noise extrapolation (ZNE)**

```
// Using unitary folding to perform
// digital zero noise extrapolation
// for a single z gate.
// d-ZNE is proposed in https://arxiv.org/pdf/2005.10921.pdf
// Example taken from https://mitiq.readthedocs.io/en/stable/guide/guide-zne.html

OPENQASM 3;
include "stdgates.inc";

bit c;

verbatim box {
    h $0;  // assume h has a defcal
    h $0;
    h $0;
}

cx $0, $1;

measure $0 -> c;
```

## **Randomized benchmarking (RB)**

```
// One randomized benchmarking sequence
OPENQASM 3;
include "stdgates.inc";

qubit q[2];
bit c[2];
verbatim(1) box {
    //assuming h, cz, s, z has defcal
    reset q;
    h q[0];
    cz q[0], q[1];
    s q[0];
    cz q[0], q[1];
    s q[0];
    z q[0];
    h q[0];
    measure q -> c;
}
```

With `verbatim box`, RB programs can be written in a clean way.

## **Flag qubit scheme in QEC [Ref [1](https://quantum-journal.org/papers/q-2018-02-08-53/pdf/), Ref [2](https://quantum-journal.org/papers/q-2019-05-20-143/pdf/)]**

```
// Flag fault-tolerant circuit for measuring the logical Hadamard
// operator of the [[7, 1, 3]] Steane code. Taken from page 6, 
// https://quantum-journal.org/papers/q-2019-05-20-143/pdf/.

OPENQASM 3;
include "stdgates.inc";

qubit steane_reg[7];
qubit flag_reg[4];

def ft_ctrl_hadamard qubit[7]: logical_qubits, 
                     qubit[1]: ancilla,
                     qubit[4] flag_qubits -> bool {
    bool success;
    
    verbatim(2) box{
        bit checks[4];
    
        x ancilla; // prepare |+>
        ch ancilla, logical_qubits[0]; 
        cx flag_qubits[0], ancilla;
        ch ancilla, logical_qubits[1];
        cx flag_qubits[1], ancilla;
        ch ancilla, logical_qubits[2];
        cx flag_qubits[2], ancilla;
        cx flag_qubits[1], ancilla;
        cx flag_qubits[3], ancilla;
        ch ancilla, logical_qubits[5];
        cx flag_qubits[3], ancilla;
        cx flag_qubits[2], ancilla;
        ch ancilla, logical_qubits[3];
        ch ancilla, logical_qubits[6];
        cx flag_qubits[0], ancilla;
        ch ancilla, logical_qubits[4];
        
        checks = measure flag_qubits;
    }
    
  success = ~(bool(checks[0]) | bool(checks[1]) |
              bool(checks[2]) | bool(checks[3]))  
              
  return success;
}
```

<img src="https://user-images.githubusercontent.com/72900809/121173822-186fa780-c80e-11eb-97eb-b7f991e181b5.png" alt="Flag qubit scheme" width="200"/>

All paired flag qubits in the lower register can be scheduled together and be cancelled, `verbatim box` will keep them intact.

In general, we suggest QEC circuits be written in a `verbatim inline box`.

# Discussion

## Higher `verbatim` levels

With `verbatim` level 1 and leve 2 introduced, we have the option to define higher `verbatim` levels for more granular control. In this PR, we do not address the problem of defining higher `verbatim` levels since there are not enough real-world examples to support it. We do provide a possible definition to demonstrate the potential use cases of higher `verbatim` levels. As an example, we can define higher levels as follows:

* level 3: composite gates, virtual qubits and gate cancellation are allowed.
* level 4: composite gates, virtual qubits, gate cancellation and gate commutation are allowed.

## Relations between `barrier` and `verbatim box`

`verbatim box` shares some similarities with `barrier` functionally in that both of them limit certain compiler optimizations and the freedom of scheduling. However, the purpose of these two do not entirely overlap. First, the effect of `verbatim box` is regional, thus, it provides a clean way for users to precisely control a long gate sequence in which case using `barrier` can be tedious and lengthy, e.g. the RB example below. Second, temporally, `barrier` is global (on the qubits it applies to) in that it blocks all gates before and all gates after from commuting. In contrast, `verbatim box `allows commutation of gates around it (e.g. the first example above in this PR). Third, there are compilation optimizations performed on single gates, such as replacing pulse-level calibration definition with more optimized ones and noise-tailoring operations like randomized compilation, that `barrier` cannot prevent but `verbatim box` can.

## Other options of the syntax

Other than the syntax we proposed, there are two other options:

* `verbatim_box`

```
verbatim_box {
     delay[20ns] q;
     x q;
     x q;
}
```

The reason we recommended the current syntax is that, if we want to introduce another kind of box, say, `nonparallel` box where no parallelization is allowed. With the `verbatim box` we can simply define `nonparallel box` or `nonparallel verbatim box`. While with `verbatim_box`, we have to define a new box `nonparallel_box`.

* `box(verbatim)`

Since `verbatim` is not an argument and the box is not a function, this syntax is not preferred.

**Comment by 1ucian0** [comment]
The may discussion around this topic it seems focus more on the syntax extension than in the semantic itself.

I talked with @aspcompiler and it seems this is a good candidate for a pragma. For example, the following annotation could mean `verbatim box`:
```
# verbatim
box {
     delay[20ns] $1;
     cx $0, $1;
     x $1;
     x $1;
}
```

**Comment by jakelishman** [comment]
I'm aware I'm coming in very new and without any of the background, but when I had first read this proposal it felt like making it a `#pragma` would offer the most flexibility, both for users and for implementations.

I had understood `#pragma` to be intended as hints or instructions for the compiler, which may be used slightly differently by different compilers (similar to how it is in C).  The "other syntax options" section gets into something similar; it suggests the idea of a `parallel_box` idea, and this is exactly something that's typically handled by `#pragma` directives in C (for OpenMP), so that different compilers or compilers without that particular feature can still parse the structure, and silently degrade to an equivalent program.

I would worry a little bit if we start having a quite restricted syntax (integer levels) for defining which compiler optimisations are allowed in a region.  As compilers gain more options, it would be a bit like trying to mandate the `-O0`, `-O1`, `-O2`, ... levels in C compilers at the language level in a way that was consistent across every possible implementation.  To extend the analogy, allowing them to be controlled instead with `-finline-functions`, `-funroll-loops` and similar via the more free-form pragma would allow different compilers to advance and add new features, without breaking `box`.

**Comment by shiyunon** [comment]
Yeah, agree with @1ucian0 @jakelishman That is also the conclusion from the last TSC meeting. I closed the PR but left the issue here. Will open it another PR for verbatim pragma.

**Comment by taalexander** [comment]
@shiyunon should we close this issue?

**Comment by shiyunon** [comment]
Closing this issue.
