### ISSUE TITLE
Request for adding Templates  for Issues and PRs

### ISSUE THREAD

**Issue by divshacker** [Qiskit/openqasm#226]
This issue is for the enhancement of this repo of adding 

- Bug_report.md
- Pull_request.md 
- Feature_Request.md ....etc

**Comment by taalexander** [comment]
I think this is a great idea. @zachschoenfeld33 could you please facilitate?

**Comment by Rassska** [comment]
Hi, do we have such examples how it should look like?

**Comment by zachschoenfeld33** [comment]
@Rassska, we have templates in Qiskit-terra that I think could be good models. See https://github.com/Qiskit/qiskit/tree/master/.github. @divshacker perhaps you could take this on when you have the opportunity?

**Comment by divshacker** [comment]
I was thinking that too. That's why I proposed to add the templates.

**Comment by divshacker** [comment]
Done @taalexander @zachschoenfeld33
