### ISSUE TITLE
Can index be negative? Document inconsistent with examples.

### ISSUE THREAD

**Issue by aspcompiler** [Qiskit/openqasm#242]
## Did you find a doc bug or broken link that needs to be fixed?

- What is the file name(s) where you found the bug?

https://qiskit.github.io/openqasm/language/types.html

- What is the current text that needs to be fixed or removed? (You can copy and paste)

```
An index set can be specified by a single unsigned integer, a comma-separated list of unsigned integers a,b,c,…, or a range. A range is written as a:b or a:c:b where a, b, and c are integers (signed or unsigned).
```

- What should the documentation say instead?

Depends on whether the example is correct or not. In the examples below, we see:

```
let last = concatenated[-1];
```

`-1` is not unsigned.

- Are there other related issues or pull requests about this bug?

Not aware of any.

## Does existing documentation need to be updated with new content?

- Which files need to be updated?

https://github.com/Qiskit/openqasm/blob/master/source/language/types.rst

Either document or example need to be updated.

- What content needs to be updated or replaced? (You can copy and paste)

Document/example inconsistency

- What new content needs to be added?

None

**Comment by 1ucian0** [comment]
I seems like a mistake `An index set can be specified by a single unsigned integer` should be `An index set can be specified by a single integer (singed or unsigned)`.

Good catch.
