### ISSUE TITLE
Bug with complex type?

### ISSUE THREAD

**Issue by aspcompiler** [Qiskit/openqasm#258]
### Informations

- **OpenQASM version**: 3.x
- **Python version**: 3.x
- **Operating system**: 3.x

### What is the current behavior?

There are a few potential issues with #175 merged on 8/16/2021.

```
singleDesignatorType
    : 'int'
    | 'uint'
    | 'float'
    | 'angle'
    | 'complex'
    ;

classicalType
    : singleDesignatorType designator
    | doubleDesignatorType doubleDesignator
    | noDesignatorType
    | bitType designator?
    | 'complex' LBRACKET numericType RBRACKET
    ;

// numeric OpenQASM types
numericType
    : singleDesignatorType designator
    | doubleDesignatorType doubleDesignator
    ;

classicalArgument
    :
    ...
    | 'complex' LBRACKET numericType designator RBRACKET Identifier
    ;
```
1. It appears that the  `complex` under `singleDesignatorType` is not needed. `classicalType` already contains a  branch for `complex`. 
2. It appears that the `complex` declaration under `classicalArgument` is not correct. The `designator` after `numericType` is not needed as `numericType` already has `designator`.

### Steps to reproduce the problem

See above.

### What is the expected behavior?

See above

### Suggested solutions

Make changes to these 2 rules:

```
singleDesignatorType
    : 'int'
    | 'uint'
    | 'float'
    | 'angle'
    ;

classicalArgument
    :
    ...
    | 'complex' LBRACKET numericType RBRACKET Identifier
    ;
```

**Comment by taalexander** [comment]
I agree there is duplication in this PR, but does it seem more consistent to keep `complex` within `singleDesignatorType` and to use `designator` rather than `numericType` within `classicalArgument`/`classicalType`?

**Comment by aspcompiler** [comment]
The only `complex` example that I found in the OpenQASM3 [paper](https://arxiv.org/pdf/2104.14722.pdf) is like:
```
complex[int[24]] iq;
```

Using the example, `'complex' LBRACKET numericType RBRACKET` is the correct syntax.

If we keep `complex` within `singleDesignatorType`, it will match to `complex[24]` but I did not find any example in the paper.

**Comment by taalexander** [comment]
I see. I was not aware that we had settled on supporting type designators of the `complex` type other than `float` (nor am I a fan of this as I believe it is overkill for almost all anticipated use cases). After reviewing the latter discussion of #175 I agree your proposal is correct for the agreed-upon syntax within the original PR. I will put forward a fix.
