### ISSUE TITLE
`include` statement is missing in `A  Open QASM Grammar` of language spec.

### ISSUE THREAD

**Issue by gyu-don** [Qiskit/openqasm#27]
`include` statement is missing in `spec/qasm2.rst` line 675-683 and `spec-human/qasm2.pdf` page 21.

**Comment by NoahGWood** [comment]
I've noticed this as well, it seems the include statement is not documented in the BNF at all.

I've just put it in with the main program so:
main: "openqasm" real ";" program | "openqasm" real ";" include program.

And I've given include its own definition as well:
include: "INCLUDE" id ";"

Seems to be working, but my parser isn't finished yet so I can't run the full test suite

**Comment by jaygambetta** [comment]
closing as this should be fixed with openqasm 3.0 which we are moving towards
