### ISSUE TITLE
Resolving stretch values uniquely

### ISSUE THREAD

**Issue by willsimmons1465** [Qiskit/openqasm#274]
## Did you find a doc bug or broken link that needs to be fixed?

- What is the file name(s) where you found the bug?

source/language/delays.rst

- What is the current text that needs to be fixed or removed? (You can copy and paste)

```
qubit[5] q;
barrier q;
cx q[0], q[1];
U(pi/4, 0, pi/2) q[2];
cx q[3], q[4];
stretch s;
delay[s] q[0], q[1];
delay[s] q[2];
delay[s] q[3], q[4];
barrier q;
```

I'm not sure this example is correct as intended. The figure showing the alignment requires the three delays to be resolved to different durations, so would this not require separate stretch variables? Otherwise, if a stretch variable can occupy different values in different locations, one could not write programs that evenly space out operations such as the following from the same page:

```
delay[start_stretch] $0;
x $0;
delay[middle_stretch] $0;
y $0;
delay[middle_stretch] $0;
x $0;
delay[middle_stretch] $0;
y $0;
delay[end_stretch] $0;
```

- What should the documentation say instead?

```qubit[5] q;
barrier q;
cx q[0], q[1];
U(pi/4, 0, pi/2) q[2];
cx q[3], q[4];
stretch s, t, u;
delay[s] q[0], q[1];
delay[t] q[2];
delay[u] q[3], q[4];
barrier q;
```

- Are there other related issues or pull requests about this bug?

Nope, this should either just be a small fix or a small clarification.

## Does existing documentation need to be updated with new content?

- Which files need to be updated?

source/language/delays.rst

- What content needs to be updated or replaced? (You can copy and paste)

The highlighted example, relating to Fig 6a

- What new content needs to be added?

None

**Comment by 1ucian0** [comment]
Closed via https://github.com/Qiskit/openqasm/pull/281
