### ISSUE TITLE
Update issue templates to latest one

### ISSUE THREAD

**Issue by divshacker** [Qiskit/openqasm#305]
GitHub has rolled out new issue forms for public repository.
https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/
Please check this out.
I recently got to know about this Feature. It will be good if we implement this in this repository.

**Comment by jwoehr** [comment]
I know that you have worked on creating such templates, @divshacker ... can you create a PR WIP of templates for this repository?

**Comment by divshacker** [comment]
Sure thanks
