### ISSUE TITLE
Switch the development branch from master to main

### ISSUE THREAD

**Issue by taalexander** [Qiskit/openqasm#327]
### What is the expected enhancement?

The standard development branch should be `main` and not `master`.

**Comment by jwoehr** [comment]
@blakejohnson @1ucian0 @ajavadia (and probably a few others) have the **owner** authority to make this adjustment.

**Comment by 1ucian0** [comment]
renamed. To rename locally, run the following commands:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
