### ISSUE TITLE
Clarify the validity of bit strings

### ISSUE THREAD

**Issue by jakelishman** [Qiskit/openqasm#334]
### What is the expected enhancement?

Currently the specification is clear that a bitstring can be used to initialise classical `bit[n]` variables:

> For convenience, classical registers can be assigned a text string containing zeros and ones of the same length as the size of the register. It is interpreted to assign each bit of the register to corresponding value 0 or 1 in the string, where the least-significant bit is on the right.
>
> ```qasm
> // Declare a register of 20 bits
> bit[20] bit_array;
> // Declare and assign a rgister of bits with decimal value of 15
> bit[8] name = "00001111";
> ```

(from [Classical bits and registers](https://qiskit.github.io/openqasm/language/types.html#classical-bits-and-registers)).

There is also a code example in [Classical value bit slicing](https://qiskit.github.io/openqasm/language/types.html#classical-value-bit-slicing) that implies that they are valid elsewhere too:

> ```qasm
> myInt[4:7] = "1010"; // myInt == 0xAF
> ```

The first paragraph only says that bit strings can be assigned to classical registers.  I think we mean something more general: a bitstring is a `bit[n]` literal and is valid whenever a `bit[n]` value would be valid.  That's implied by the second example, and needed in equality comparisons:
```qasm
bit[4] cr;
// ...
if (cr == "1001") {
    // ...
}
```
If so, a small text update to clarify this would be good.

**Comment by jwoehr** [comment]
@jakelishman are you going to submit a PR that provides the desired clarification?

**Comment by blakejohnson** [comment]
I agree with your interpretation, @jakelishman.

**Comment by jakelishman** [comment]
#337 touches this, and since I need to take over that PR anyway, I'll fix this issue as part of that.
