### ISSUE TITLE
Arguments cannot be indexed within the body of the gate definition. Why?

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/openqasm#37]
Playing with the parser, I noticed that the specification does not allow registers to be indexed in the gate definition. What's the rationale behind that?

**Comment by ismaelfaro** [comment]
The current parser is a draft that we need to continue to iterate it.

**Comment by 1ucian0** [comment]
this probably refers to OpenQASM2 (since I submitted in 2018). Time to close it.
