### ISSUE TITLE
Benchmarks are not working on version 0.6.1

### ISSUE THREAD

**Issue by adamisntdead** [Qiskit/openqasm#39]
Due to the changes in 0.6.1, the benchmarks don't work any more,

Happy to take a look at it btw.

**Comment by ajavadia** [comment]
@adamisntdead Thanks for checking. We are going to move benchmarks to a global repository fairly soon where they will act as integration tests for the compiler, simulator, etc.
But I agree that they should be fixed here first. If you want to take a crack at it, please do!

**Comment by wh5a** [comment]
Any updates on the new integration tests?
