### ISSUE TITLE
cRz and cU1 gates not completely equivalent?

### ISSUE THREAD

**Issue by g-ebbs** [Qiskit/openqasm#52]
_Hello! I am new to the Qiskit Github page but I have been working on an undergraduate research project utilizing openQASM for the past year. During this time I have come across a couple of bugs/inconsistencies that I hope to revisit and share on this page. Disclaimer: I am still new to quantum computing and mostly self-taught, so I apologize in advance for any errors/misunderstandings. I have developed a real passion for the subject and I'm looking forward to getting involved more in the community!_

### Problem: 
The cRz and cU1 gates are listed as equivalent in the gates glossary but seem to provide different results when applied to an initial superposition of H gates. There seems to be an extra overall phase factor involved that is not referenced in the definitions of the gates.

![image](https://user-images.githubusercontent.com/59269494/73697059-ab914e00-46ab-11ea-8320-df813aae0599.png)

### Steps to Reproduce the Problem:
Examples of each gate:
![image](https://user-images.githubusercontent.com/59269494/73697190-f612ca80-46ab-11ea-9384-fdf8d93aca34.png)

OPENQASM 2.0;
include "qelib1.inc";

qreg q[3];
creg c[3];

h q[0];
h q[1];
h q[2];
crz(pi/2) q[0],q[2];

![image](https://user-images.githubusercontent.com/59269494/73697218-062aaa00-46ac-11ea-8536-ce6571fde4bf.png)

OPENQASM 2.0;
include "qelib1.inc";

qreg q[3];
creg c[3];

h q[0];
h q[1];
h q[2];
cu1(pi/2) q[0],q[2];

### Comments:
Are these differences in phase normal? If so, I would suggest noting this in the glossary because as a beginner I found it a little confusing. Alternatively, if I did something out of the ordinary or do not have a complete understanding of these gates let me know. I'm excited to contribute and continue learning!

**Comment by hexadec** [comment]
As another beginner, I would simply like to point out, that these differences seem normal according to their definitions here:
https://github.com/Qiskit/openqasm/blob/master/examples/generic/qelib1.inc

**Comment by g-ebbs** [comment]
> As another beginner, I would simply like to point out, that these differences seem normal according to their definitions here:
> https://github.com/Qiskit/openqasm/blob/master/examples/generic/qelib1.inc

I found some time to go over the math since posting this issue and I agree @hexadec, the code is correct. I think the issue is related to how the gates are defined in the glossary. Not sure if this was the correct place to discuss this issue since it is not directly related to the qasm code, my mistake.

**Comment by jaygambetta** [comment]
sorry just seeing this the are different. They are the same without the control as global phase does not matter but when you add a control the global phase becomes a relative phase and as such they do different things.
