### ISSUE TITLE
Add table of contents to live document

### ISSUE THREAD

**Issue by blakejohnson** [Qiskit/openqasm#66]
Landing page for live document should be something like: https://webassembly.github.io/spec/core/

**Comment by ismaelfaro** [comment]
or at least have the "current version" on the top, and a one level more in the Left index, for now.

**Comment by delapuente** [comment]
Agree. I tried to do it quickly but the default generator for a single HTML site gets rid of the global content table. We can mimic what WebAssembly is doing quickly by splitting the site into several pages. Are we good with it?

**Comment by blakejohnson** [comment]
Yes, the site should be several pages.
