### ISSUE TITLE
Images are missing from live doc

### ISSUE THREAD

**Issue by blakejohnson** [Qiskit/openqasm#68]
Circuits and stretch diagrams are missing from the live doc.

**Comment by delapuente** [comment]
We need a way of translating [tikzpicture](https://www.overleaf.com/learn/latex/TikZ_package) files into SVGs first. Also, think about how to continue creating this kind of pictures later, and if we want to keep the original files too.

**Comment by ismaelfaro** [comment]
I just fixed the .tex files, to generate the PDF >> SVG versions.
PR #84

**Comment by blakejohnson** [comment]
Any update on this, @delapuente ?

**Comment by delapuente** [comment]
I'm working on this. The converted images were missing some symbols. I'm coming up with an automatized method to do it relying on LaTeX tools and `pdftocairo`. Also, the lack of some kind of multi-image figure for Sphinx is also very convenient so I'm creating an extension to support it. I hope to have it ready by the end of this week, early next.
