### ISSUE TITLE
"inc" files allowed in "include"

### ISSUE THREAD

**Issue by zachschoenfeld33** [Qiskit/openqasm#99]
Based on the examples, files with either the `qasm` or `inc` specifier are allowed in `include`, however only `.qasm` is included in the live specification.

**Comment by taalexander** [comment]
I don't think it should matter. Since it's a filepath it should just be treated as QASM3 regardless of the file extension.

**Comment by zachschoenfeld33** [comment]
Well for parsing it, I don't think I should be opening up the file and adding all of it?

**Comment by taalexander** [comment]
No, that is the responsibility of the compiler to link/preprocess.

**Comment by zachschoenfeld33** [comment]
It just seems like only one extension is allowed in the specification, but it really should be any string w/ any file type.

**Comment by taalexander** [comment]
Yes, from a parser's perspective.

**Comment by zachschoenfeld33** [comment]
I think this should be made clearer, I can make a PR if we want about it

**Comment by taalexander** [comment]
Sure, please see https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html.

**Comment by zachschoenfeld33** [comment]
Looks like it was clarified. Was a minor spelling error, so added PR: https://github.com/Qiskit/openqasm/pull/105. Closing this issue.
